### ISSUE TITLE
mods contributor rspec alignment

### ISSUE THREAD

**Issue by ndushay** [sul-dlss-labs/cocina-descriptive-metadata#298]
https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/from_fedora/descriptive/contributor.rb  and https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cocina/to_fedora/descriptive/contributor.rb  are long, but hopefully organized well for you to assess:

1. prioritization of mappings that haven't yet been done
2. discrepancies between our rspec code and your mapping examples - should we update our code (we'll need a ticket in dsa) or should you update your mapping?  I tried to mark these with `FIXME: discrepancy`
    - [ ] from_fedora, line (missing `type="name"` in `structuredValue`), line 1256 [AF: doesn't match problem in code comment, for that problem https://github.com/sul-dlss/dor-services-app/issues/1822]
    - [x] to_fedora example 7b, line 394 [AF: #300 and #301  ]
    - [x] to_fedora example 7c, line 469 [AF: #302 ]
    - [x] to_fedora example 7e, line 549 [AF: #303 ]
    - [x] to_fedora example 12, line 1060 [AF: #304, https://github.com/sul-dlss/dor-services-app/issues/1824]
    - [ ] to_fedora example from title name with authority, 6, line 985 [AF: #306  before dsa ticket can be filed]
3. whether to add examples to mods_to_cocina_name.txt.  I've noted some that seem likely (there are MORE - please look), but I'll leave it to you:
    - [x] name missing type, to_fedora line 215 [AF: #307 ]
    - [x] missing nameIdentifier type, from_fedora line 329 [AF: #308 ]
    - [x] multiple nameParts without types, from_fedora line 359 and to_fedora 312 [AF: #309 ]
    - [ ] role that has no URI and has xlink uris from MODS 3.3, from_fedora line 499 [AF: data remediation, https://github.com/sul-dlss/dor-services-app/issues/1826]
    - [x] translated name, no role, to_fedora line 148 [AF: https://github.com/sul-dlss/dor-services-app/issues/1827]
    - [x] translated name and roles, from_fedora line 546 [AF: #310]
    - [x] role text has no authority, from_fedora line 714, to_fedora line 435 [AF: #311]
    - [x] role code is missing the authority and length is 3, from_fedora line 784 [AF: #312]
    - [x] multiple roles, from_fedora line 980, to_fedora 673 [AF: #313]
    - [x] multiple names, one primary, dates, no roles, from_fedora line 1106, to_fedora line 834 (I'm on the fence) [AF: #314]

Calling out that you can have examples numbered, e.g. 11a.1 or whatever if you want to insert between already assigned lettered "numbers"

**Comment by arcadiafalcone** [comment]
In the first checkbox under no. 2, "from_fedora, line (missing type="name" in structuredValue), line 1256", I'm not seeing a missing name, but I am seeing a missing "status": "primary", so that's what I ticketed.

**Comment by arcadiafalcone** [comment]
https://github.com/sul-dlss/dor-services-app/blob/9bf656819ebf93ccd103d846dd1fa348dca89a6f/spec/services/cocina/from_fedora/descriptive/contributor_spec.rb#L499
This is a metadata remediation issue - the xlink should link to actual content (the text of an abstract for example) rather than to an authority.
